# Generated by Django 5.1.5 on 2025-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
