# Generated by Django 5.1.5 on 2025-08-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_password_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='staff',
        ),
    ]
