# Generated by Django 5.1.5 on 2025-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sale_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_address',
            field=models.TextField(default='Unknown', max_length=200),
        ),
    ]
