# Generated by Django 5.1.5 on 2025-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sale_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='Not Delivered', max_length=20),
        ),
    ]
