# Generated by Django 5.1.5 on 2025-08-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sale_delivery_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
